### PR TITLE
Add support for SSL

### PR DESCRIPTION
**Pull request by mattusifer**
### Overview

This PR adds an optional `sslContext` argument to the `RedisClient` and `RedisClientPool` classes. If an `sslContext` is provided, the underlying socket will be wrapped with an `SSLSocket` layer.

### Testing
This PR uses the `madflojo/redis-tls:latest` image ([source](https://github.com/madflojo/redis-tls-dockerfile)) to run a redis test container that will only accept connections over SSL. I've included a self-signed certificate/key pair that is used by this container to encrypt the connection to redis.

Resolves https://github.com/debasishg/scala-redis/issues/254 and Resolves https://github.com/debasishg/scala-redis/issues/230

### CODE REVIEW

**Comment by debasishg** [comment]
Thanks a lot ..

**Comment by mattusifer** [comment]
Thanks @debasishg ! Let me know if there's any way we can cut a new release with this feature soon.

**Comment by debasishg** [comment]
I will have a release soon .. Thanks for the PR ..

**Comment by debasishg** [comment]
Released `3.3.0` today ..

**Pull request merged**
