### PR TITLE
feat: add .travis.yml

### PR DESCRIPTION
**Pull request by masahitojp**
related: #223 

I have confirmed that the unit test has passed
https://travis-ci.org/masahitojp/scala-redis/builds/430678815

### CODE REVIEW

**Comment by debasishg** [comment]
Thanks .. we tried adding this long back. Faced some problems.

**Comment by masahitojp** [comment]
@debasishg 
> Faced some problems.

How about this?Please share it if you like. 😄

**Comment by debasishg** [comment]
It works :-) .. I would like to share this on Twitter. Can u pls let me know ur twitter handle ?

**Comment by masahitojp** [comment]
@debasishg 

> It works :-)

Glad to hear that :-)
My Twitter handle is `@Masahito` https://twitter.com/masahito

**Pull request merged**
