### PR TITLE
Add redis TIME command

### PR DESCRIPTION
**Pull request by dqdinh**
Add support for https://redis.io/commands/time

### CODE REVIEW

**Comment by debasishg** [comment]
Thanks!

**Comment by dqdinh** [comment]
Thanks for the quick turn around!

I'm still new to SBT and Scala OSS, do you know when a new version of the library will get released with this change?

**Comment by debasishg** [comment]
I will try and get a release out over the coming weekend. Is that ok ?

**Comment by dqdinh** [comment]
Sounds good! Thanks.

**Comment by debasishg** [comment]
Released just now. Will take time to sync with Maven Central ..

**Comment by dqdinh** [comment]
Awesome. Thanks!

**Pull request merged**
